export const Lookups = {
    Currency: 1 ,
    Country:2,
    mode:3,
    Group:4,
    periodicity:5,
    days:6,
    month:7,
    gender:8,
    marital_Status:9,
    Contract_Type:10,
    EmployeeStatus:11,
    parttime:12,
    salarystatus: 13,
    paymentmethod: 14,
    Title:15,
    lawtypes:16,
    Declaration:17,
    StaffCategory:18,
    Entitlement:19
}